package exceptionPackage;

public class CheckedExcep2 {

	public static void main(String[] args) {

		System.out.println("Programme starts");
		
		int num[]= {1, 2, 5,7,8};
		System.out.println(num[5]);//ArrayIndexOutOfBoundsException--runtime exception

		System.out.println("Programme Ends");

	}

}
